# Generated by Django 5.2.15 on 2026-06-15 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='llm_provider',
            field=models.CharField(choices=[('groq', 'Groq'), ('openai', 'OpenAI'), ('gemini', 'Gemini')], default='groq', max_length=50),
        ),
    ]
